### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [andrewrk/malcheck#1]
Would you like to add more error handling for [a failed call](https://github.com/andrewrk/malcheck/blob/7fdcca54aa45c03eb1bae691f07695e021e7a3ac/src/libmalcheck.c#L112) of [a function like pthread_mutex_lock()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html)?

**Comment by andrewrk** [comment]
I'm not sure how to handle mutex lock failures. How would you handle it?

**Comment by elfring** [comment]
How do you think about to make this implementation detail configurable so that the user of your tool can select the preferred error reaction?

**Comment by andrewrk** [comment]
What other action could the tool take besides crashing? If the mutex locking did not work, then the tool cannot carry on.

**Comment by elfring** [comment]
Which error reaction would your users prefer?
- exit(errno)
- abort()
- Custom error reporting function

**Comment by andrewrk** [comment]
OK wait a minute. I researched this when I wrote the code. The only return codes of `pthread_mutex_lock` and `pthread_mutex_unlock` are:

```
EINVAL
The mutex was created with the protocol attribute having the value PTHREAD_PRIO_PROTECT and the calling thread's priority is higher than the mutex's current priority ceiling.
The pthread_mutex_trylock() function shall fail if:

EBUSY
The mutex could not be acquired because it was already locked.
The pthread_mutex_lock(), pthread_mutex_trylock(), and pthread_mutex_unlock() functions may fail if:

EINVAL
The value specified by mutex does not refer to an initialized mutex object.
EAGAIN
The mutex could not be acquired because the maximum number of recursive locks for mutex has been exceeded.
The pthread_mutex_lock() function may fail if:

EDEADLK
The current thread already owns the mutex.
The pthread_mutex_unlock() function may fail if:

EPERM
The current thread does not own the mutex.
```

All of these conditions are logic errors in malcheck code, which means it will never happen unless there is a bug in malcheck. So the only thing to do here is assert.

**Comment by elfring** [comment]
Can inappropriate values eventually occur even if your function implementation does not contain a logic error?

I do not like [the use of the assert macro](https://github.com/andrewrk/malcheck/commit/c973d89cc307ed3574a60a3a23c2fd5c535bc492#diff-a13002b4ba9b2abc77b18037e588e7deR116) because unexpected results will still be ignored if the preprocessor symbol "`NDEBUG`" will be defined. I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.

**Comment by andrewrk** [comment]
Consider the following code:

``` c
int my_int = 8;
int *ptr = &my_int;
assert(ptr);
int my_other_int = *ptr;
```

This code does not cause a segfault. In fact it is so obvious that it does not cause a segfault that the assertion is probably unnecessary. I could do this:

``` c
int my_int = 8;
int *ptr = &my_int;
if (!ptr) {
    fprintf(stderr, "unexpected null pointer\n");
    abort();
}
int my_other_int = *ptr;
```

But this would be pointless, since ptr cannot be null at that location.

Likewise in malcheck, it is impossible for `pthread_mutex_lock` to return an error. The assertion is "just in case" a bug happens now or some time in the future to catch it.

Really, the assertions in malcheck for locking I don't think are necessary since the code is so short and simple, but it's no harm to have them there.

**Comment by elfring** [comment]
> …, it is impossible for pthread_mutex_lock to return an error. …

This function from the POSIX programming interface can generally return also an error code.
Do you know how big the probability for a failure from the corresponding statement "`static pthread_mutex_t init_mutex = PTHREAD_MUTEX_INITIALIZER;`" can be?

Would you like to care for a failure from a call of the function "vfprintf"?

**Comment by andrewrk** [comment]
> Do you know how big the probability for a failure from the corresponding statement "static pthread_mutex_t init_mutex = PTHREAD_MUTEX_INITIALIZER;" can be?

My understanding is 0. How is it possible for this to fail?

> Would you like to care for a failure from a call of the function "vfprintf"?

Yes, you're right. I should handle the failure from vfprintf and fprintf.

**Comment by elfring** [comment]
How do you think about answers from other software developers?

Example topics:
- [Static-Initializer <errno.h> Failure Value's...](http://compgroups.net/comp.programming.threads/static-initializer-errno.h-failure-v/476907)
- [C++ correct use of mutex](http://stackoverflow.com/questions/5836538/c-correct-use-of-mutex#answer-5836770)

**Comment by andrewrk** [comment]
According to the article you linked, static initializers cannot fail, which is what I originally claimed.

Can you be more explicit with what you are suggesting? This Socratic Method thing is less efficient than direct arguments, and it comes off as a bit condescending.

**Comment by elfring** [comment]
Do you get further ideas from an archived answer by David Butenhof (on 2007-11-05) like the following?

```
…
POSIX is a standard. By design and intent, POSIX does not attempt
to prevent implementations of the standard from extending the standard
in a variety of ways and for a variety of reasons.

In particular, an implementation is allowed to report additional errors 
not documented by the standard, for any function, unless specifically prohibited.
…
```

**Comment by andrewrk** [comment]
This is a bot account. Really brilliant troll, whoever did it. :100: 

https://github.com/ziglang/zig/issues/1087#issuecomment-395991802
